### ISSUE TITLE
Rubocop was updated

### ISSUE THREAD

**Issue by jjasghar** [SumoLogic/sumologic-collector-chef-cookbook#106]
https://jenkins-01.eastus.cloudapp.azure.com/job/sumologic-collector-cookbook/99/console

It looks like yall need to pin your rubocop version.

**Comment by jjasghar** [comment]
https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/107

**Comment by majormoses** [comment]
the issue from what I can tell is not so much that its not pinned in Gemfile. Its that in `travis.yml` it using the chefdk version of rubocop which is not pinned. I am gonna propose changing this along many other CI improvements...

**Comment by majormoses** [comment]
I am going to solve this (and many others) via: https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/134

**Comment by majormoses** [comment]
closed via #134
