### ISSUE TITLE
converge_by is causing constant restarts of the collector service

### ISSUE THREAD

**Issue by dannenberg** [SumoLogic/sumologic-collector-chef-cookbook#112]
We wrapped this cookbook in our own. Ours contains a single recipe which generates resources based on an attribute as follows:
```
node['tpt-sumologic']['local_file_sources'].each do |attributes|
  sumo_source_local_file attributes['source_name'] do
    source_json_directory node['sumologic']['sumo_json_path']
    attributes.each do |a, v|
      if a == 'category'
        send(a.to_sym, "#{node.chef_environment}/#{v}")
      else
        send(a.to_sym, v)
      end
    end
    notifies :restart, 'service[collector]', :delayed
  end
end
```

The notifies line is triggering a restart on each run, even though the files do not change. The output from a run of this recipe is as follows:
```
  * sumo_source_local_file[core_web_app] action create
    - Create /etc/sumo/core_web_app.json
    * file[/etc/sumo/core_web_app.json] action create (up to date)
  
  * sumo_source_local_file[chef-client] action create
    - Create /etc/sumo/chef-client.json
    * file[/etc/sumo/chef-client.json] action create (up to date)
```

I believe the lines starting with `- Create` indicate that the resource is being created even though there was no change. I think this is caused by the use of `coverge_by` in the [provider](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/libraries/provider_source.rb#L20-L36). I think using [converg_if_changed](https://docs.chef.io/custom_resources.html#converge-if-changed) instead would prevent the files from being created when they are already present and up to date, which would, in turn, prevent our constant restarts.

I'd be happy to use another work around if you know of one.  Thanks for your help!

**Comment by duchatran** [comment]
Merged to master. Thanks for contributing @dannenberg
