### ISSUE TITLE
Permit the setting of the category when creating the default config files

### ISSUE THREAD

**Issue by aquantumofdata** [SumoLogic/sumologic-collector-chef-cookbook#115]
When a the recipe uses a source folder 2 default config files are created. 

Currently the category is hardcoded.

It would be nice to permit this to be over-ridden to allow people to follow their orgs standards.

**Comment by aquantumofdata** [comment]
https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/116

**Comment by duchatran** [comment]
PR merged.
