### ISSUE TITLE
How do i store access id and key in data bags?

### ISSUE THREAD

**Issue by luckytaxi** [SumoLogic/sumologic-collector-chef-cookbook#135]
New chef user ...

I have a data bag called "sumo-creds" with an item called "api-creds."

    # cat api-creds.json
    {
       "id": "api-creds",
       "accessID": "XXXXXXX",
       "accessKey": "XXXXXXXXXXXXXXXXXXXXXX"
    }

How do I reference it in my recipe?

```
sumologic_collector '/opt/SumoCollector' do
  collector_name node['datadog']['hostname']
  sumo_access_id ???
  sumo_access_key ???
  action :configure
end
```

**Comment by majormoses** [comment]
The short answer is yes that databg looks ok (though you should encrypt it at least (documentation here: https://docs.chef.io/data_bags.html). you just need to be able to access those from the data bag I do something like this when accessing data bag properties:
### get the dbag name from attributes
```ruby
creds_dbag_item = data_bag_item(
  node['sumologic']['credentials']['bag_name'],
  node['sumologic']['credentials']['item_name']
)
```

### creds need to be symbols last I checked I do something like this
```ruby
credentials = {}

[:accessID, :accessKey, :email, :password].each do |sym|
  credentials[sym] = creds_dbag_item[sym.to_s] # Chef::DataBagItem 10.28 doesn't work with symbols
end
```

### access the properties:
```ruby
sumologic_collector '/opt/SumoCollector' do
  collector_name node['datadog']['hostname']
  sumo_access_id credentials[:accessID]
  sumo_access_key credentials[:accessKey]
  action :configure
end
```

**Comment by majormoses** [comment]
Let me know if this works for you.

**Comment by luckytaxi** [comment]
perfect thx
