### ISSUE TITLE
Chef 13 compatibility

### ISSUE THREAD

**Issue by nshemonsky** [SumoLogic/sumologic-collector-chef-cookbook#140]
This is just a question rather than an issue. I see that commit https://github.com/SumoLogic/sumologic-collector-chef-cookbook/commit/37f20fede75d1d4f732e8264129106f411e3514e enables Chef 13 compatibility. Just wondering if a tagged release including that commit is planned any time soon?

Thanks.

**Comment by luckytaxi** [comment]
Ran into this today.

**Comment by shinitiandrei** [comment]
I saw that commit as well, but when testing in Chef 13.2.20 I receive the following error:

`================================================================================
           Error executing action `install_and_configure` on resource 'sumologic_collector[/etc/sumo]'
           ================================================================================
           
           NameError
           ---------
           uninitialized constant Chef::Resource::SumologicCollector
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/sumologic-collector/providers/default.rb:10:in 
 load_current_resource'
`

Having a look at the code, there is a block of code trying to use the SumologicCollector constant:
```ruby
ruby_block 'Wait for Sumo Collector to register' do
    block do
      SumologicCollector::Helpers.wait_for_registration(new_resource.dir)
    end
  end
```

I am not an expert in Ruby but that seems to be the problem...any help/update would be appreciated :)
Thanks!

**Comment by nshemonsky** [comment]
This was taken care of in 96af5f1 with release v1.2.22. Thanks.
