### ISSUE TITLE
Support eventFormat and eventMessage attributes for Windows events

### ISSUE THREAD

**Issue by ethan-motion** [SumoLogic/sumologic-collector-chef-cookbook#187]
To convert Windows events to JSON, the cookbook needs to support the `eventFormat` and `eventMessage` attributes.

https://help.sumologic.com/03Send-Data/Sources/01Sources-for-Installed-Collectors/Local-Windows-Event-Log-Source

**Comment by JSamX** [comment]
+1 this please

**Comment by astencel-sumo** [comment]
Fixed in #193 
Released in [v1.7.0](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/releases/tag/v1.7.0)
