### ISSUE TITLE
LWRP for Update

### ISSUE THREAD

**Issue by sumoway** [SumoLogic/sumologic-collector-chef-cookbook#21]

**Comment by agperson** [comment]
We continue to run into API endpoint rate limiting issues; being able to manage sources via an LWRP that writes out JSON is still much needed.

**Comment by duchatran** [comment]
Thanks everyone, is this issue still relevant? The new cookbook leverages the Local File Configuration Management feature (https://service.sumologic.com/help/Default.htm#Using_Local_Configuration_File_Management.htm?Highlight=Log Management) which I believe is more suitable for automation tools.

**Comment by sumoway** [comment]
Nope, local config file management does make this irrelevant
