### ISSUE TITLE
Metadata version bump

### ISSUE THREAD

**Issue by anowell** [SumoLogic/sumologic-collector-chef-cookbook#24]
Could we get a version bump and release to the chef supermarket?

I'm specifically looking to pull in #20, and currently pointing Berkshelf at a specific git revision for lack of release.

**Comment by pdunnavant** [comment]
With the latest changes, is there any way that the metadata version can be bumped again along with another release to https://supermarket.chef.io/cookbooks/sumologic-collector?

**Comment by sumoway** [comment]
Done!  Thank you @pdunnavant
