### ISSUE TITLE
Bad release on supermarket

### ISSUE THREAD

**Issue by coderanger** [SumoLogic/sumologic-collector-chef-cookbook#28]
Currently the latest version available via supermarket is `1.2.02`. This sorts higher than `1.2.1` because Chef (and related tools) just treat versions as three integers, so `1.2.02` == `1.2.2`. This doesn't look to be what you intended. You can either yank the `02` release from Supermarket or just release something higher than both (eg. `1.2.3`). If you have any questions on versions or sorting, please let me know.

**Comment by pdunnavant** [comment]
:+1: Agreed. I just got all confused by this as well.

**Comment by sumoway** [comment]
Sorry for the delay on this one guys.  The supermarket is on 1.2.3 now.  Thanks for bringing this up.
