### ISSUE TITLE
SumoLogic never starts on windows

### ISSUE THREAD

**Issue by mikepugh** [SumoLogic/sumologic-collector-chef-cookbook#29]
After adding this cookbook and configuring credentials, SumoLogic did get installed on my windows host, but the recipe never started the service.

When I went to manually start the service, just to test out the setup, it complained that the sumo.conf file was gone. This file gets removed as part of the cleanup recipe.

**Comment by mikepugh** [comment]
It turns out the issue was related to a secret key encoding problem ('invalid byte sequence in UTF-8') which resulted in no sumo.conf file being created, which meant the service failed to start. Now that the key issue is resolved, sumo was able to install, connect, and start up.

**Comment by sumoway** [comment]
Right on.  Thank you Mike!
