### ISSUE TITLE
This cookbook should allow to be re-run

### ISSUE THREAD

**Issue by xbeta** [SumoLogic/sumologic-collector-chef-cookbook#31]
https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/recipes%2Fdefault.rb#L29

What happen if we need to re-run this though the install folder already existed?
Then nothing else will get run?

**Comment by duchatran** [comment]
You can delete the folder where collector is installed, if this is a reinstall scenario.

**Comment by lmickh** [comment]
What is the logic behind this decision?  

It seems like a natural use case to want to reconfigure a client via chef attributes without having to delete the install folder for a change to take place.  The current setup sort of nullifies the reason for using Chef in the first place.  It does nothing to ensure the configuration of the software so long as a single dir exists.
