### ISSUE TITLE
Commit f4b55675d07e5f6b89d54b3406320e7dc58d0c1b removes customization for install

### ISSUE THREAD

**Issue by DanielRedOak** [SumoLogic/sumologic-collector-chef-cookbook#42]
Moving from tar installs to dep/rpms effectively removes the customization around install paths, etc.  Instead of completely removing this, I would suggest making it selectable via attribute such as node['sumologic']['install_type'] = {package | tar }

**Comment by majormoses** [comment]
I'd take a pr to allow choosing an install method.

**Comment by majormoses** [comment]
It looks like we support tar based installs. Closing as I think we have support and lack of activity.
