### ISSUE TITLE
Thoughts on defining Sumo sources across multiple cookbooks?

### ISSUE THREAD

**Issue by RoboticCheese** [SumoLogic/sumologic-collector-chef-cookbook#43]
Because Chef's attribute merging can be a little wonky for arrays (as described [here](https://coderanger.net/arrays-and-chef/) and [here](http://lists.opscode.com/sympa/arc/chef/2013-10/msg00383.html), things quickly get weird if someone has multiple application cookbooks that each need to configure their own sources.

Right now, something like this results in the two attributes clobbering each other:

```
cookbooks/foo/attributes/default.rb:

default['sumologic']['sources'] = [{name: 'foo'...}]

cookbooks/bar/attributes/default.rb:

default['sumologic']['sources'] = [{name: 'bar'...}]
```

Converting `node['sumologic']['sources']` to a hash would allow one to build up a set of Sumo sources:

```
cookbooks/foo/attributes/default.rb:

default['sumologic']['sources']['foo'] = {name: 'foo'...}

cookbooks/bar/attributes/default.rb:

default['sumologic']['sources']['bar'] = {name: 'bar'...}
```

At a glance, it looks like it wouldn't be too much work to support that attribute being either an array or hash. A slightly more complex alternative might involve a custom resource for people to use in their recipes that, during the Chef run, would combine to form the `sumo.json`:

```
cookbooks/foo/recipes/default.rb:

sumologic_source 'foo' do
  source_type 'LocalFile'
  time_zone 'UTC'
  ...
end
```

I'd be happy to work on a PR for either approach; just wanted to check for folks' opinions first.

Thanks!

**Comment by kennonkwok** [comment]
:+1: @akemner and I were literally just talking about this 20 mins ago!  the custom resource approach would be rad.

**Comment by lmickh** [comment]
:+1: 

I've worked around this in a wrapper cookbook by setting a hash and then node.default['sumologic']['sources'] = hash.values.  Would be much better if the cookbook used hashes natively.  A custom resource would be even better.

**Comment by kennonkwok** [comment]
FWIW, there is a conf.d/ style feature that isn't well documented.  There's a decent discussion about it here: https://support.sumologic.com/hc/communities/public/questions/203916378-Multiple-sources-json-for-syncSources-feature

I'll be testing this out shortly

**Comment by kennonkwok** [comment]
Here's a gist with the sumo.conf and a couple source json files: https://gist.github.com/kennonkwok/7189c27d6615a4e1d150

**Comment by kevindickerson** [comment]
Hi, I'm KKennon and I discussed this issue this morning. We agree that a resource would be the best approach! I'll prepare a PR soon.

**Comment by RoboticCheese** [comment]
@kevindickerson Awesome! I kept meaning to work on it after opening this issue but other things kept getting in the way. :heart:

**Comment by kevindickerson** [comment]
No problem. I'll have it out and we can take a look at it tomorrow!

**Comment by kevindickerson** [comment]
@RoboticCheese @lmickh Being not an expert at Sumologic, I'm trying to find out where a JSON 'source' file should actually go... Any ideas?

**Comment by kennonkwok** [comment]
What would folks think if the resource looked like this?
```
sumologic_source 'messages' do
    source_json '{
      "api.version": "v1",
      "source":
        {
          "name": "Messages",
          "sourceType": "LocalFile",
          "automaticDateParsing": true,
          "multilineProcessingEnabled": false,
          "useAutolineMatching": true,
          "forceTimeZone": false,
          "timeZone": "UTC",
          "category": "OS/Linux/System",
          "pathExpression": "/var/log/messages"
        }
      }'
  end
```
The thought being that this is pretty easy to implement vs writing something that validates all of the rules for the various source types and it would be less brittle on the chef code side.  Downside is that whoever is working with it will need to minimally know how to configure a sumologic source with the json syntax.

**Comment by mikepugh** [comment]
@kennonkwok I like that approach. Knowing the JSON syntax isn't a huge burden and it ties in with the SumoLogic documentation nicely.

**Comment by kevindickerson** [comment]
@kennonkwok :+1:
