### ISSUE TITLE
Usage on Amazon Linux?

### ISSUE THREAD

**Issue by moneill** [SumoLogic/sumologic-collector-chef-cookbook#48]
Hi there! I'm trying to use this cookbook with Amazon Linux-based hosts. The cookbook's [metadata](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/metadata.rb#L25) suggests that `amazon` is a supported platform but the [`sumologic-collector::install`](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/recipes/install.rb#L39) recipe does not seem to have a case that covers the `amazon` platform. As a result, that recipe doesn't get applied, so the collector never actually gets installed.

Would there be value in adding `amazon` to the list of supported [platforms](https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/recipes/install.rb#L39) for the RPM installer? I'll admit that my testing so far has been extremely limited, but doing so does appear to get the collector installed on our Amazon Linux boxes.

**Comment by jcadarsh** [comment]
I created a pull request to rectify this. https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/53

**Comment by sumoway** [comment]
Thank you @jcadarsh !
