### ISSUE TITLE
Install recipe doesn't run for windows

### ISSUE THREAD

**Issue by sinkingpoint** [SumoLogic/sumologic-collector-chef-cookbook#50]
A recent change pulled the logic for installing on windows out into its own recipe ("windows"), but this is not included in the install recipe. This means that running the default cookbook fails to install on windows. In addition, if one runs the default recipe, it creates the folder structure which stops the windows recipe from running its installation so the folders have to be removed manually before the cookbook is re run. 

it would be nice to see the logic for including the windows recipe included in the install one. i.e. add

```ruby
    when 'windows'
         include_recipe 'sumologic-collector::windows'
```

to the switch statement in install.rb in order to make the install process smoother.

**Comment by Z3r0Sum** [comment]
I'm also seeing an issue around this where the sumologic-collector::install recipe just gets run every chef is run.  So it essentially is redeploying every time.

**Comment by sumoway** [comment]
This issue has been resolved in recent commits.  The organization of files has changed so the fix is different from what you have here, but the Test Kitchen Windows suites are passing.
