### ISSUE TITLE
Databag isn't decrypted when using data_bag_item and chef 11 client

### ISSUE THREAD

**Issue by vandadck** [SumoLogic/sumologic-collector-chef-cookbook#51]
sumoconf.rb line 39

[...]
  else
    bag = data_bag_item(creds[:bag_name], creds[:item_name])
  end

It puts the encrypted data bag values in the sumoconf.rb.

Old method below works fine
    bag = Chef::EncryptedDataBagItem.load('sumo-creds','api-creds')

**Comment by majormoses** [comment]
@vandadck apologies on that, I would be more inclined to get this fixed if we were not about to drop chef < 12 support. If you want to get it in before we do that I would take a PR.

**Comment by majormoses** [comment]
closing as chef 11 is now 3 major releases behind the current stable.
