### ISSUE TITLE
sumo service is "collector" not "sumo-collector"

### ISSUE THREAD

**Issue by lindsay-apitalent** [SumoLogic/sumologic-collector-chef-cookbook#61]
Referenced in recipies/default.rb

**Comment by duchatran** [comment]
@lindsay-apitalent: on Windows boxes it should indeed be sumo-collector.  Do you see collector on yours?

**Comment by lindsay-apitalent** [comment]
on linux its collector

On 27 February 2016 at 13:20, Duc Ha <notifications@github.com> wrote:

> @lindsay-apitalent <https://github.com/lindsay-apitalent>: on Windows
> boxes it should indeed be sumo-collector. Do you see collector on yours?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SumoLogic/sumologic-collector-chef-cookbook/issues/61#issuecomment-189535082>
> .
>



-- 
Lindsay Parker
Cloud Infrastructure Architect
Mobile: 021 5995 40

---
API Talent, 150 Featherston Street, Wellington
Telephone  04 979 9631 :: Email hello@apitalent.co.nz
www.apitalent.co.nz

**Comment by duchatran** [comment]
Reopen to accommodate different service names on different platforms ("sumo-collector" on windows, "collector" on Linux).

**Comment by majormoses** [comment]
whats the reasoning for the name difference? I think a service named "collector" is way too generic...

**Comment by duchatran** [comment]
Fixed in 1.2.15

**Comment by duchatran** [comment]
@majormoses: That's our bad, I think we are just inconsistent :(

**Comment by majormoses** [comment]
@duchatran any reason you chose to make it "collector" and not "sumlogic-collector" when fixing? The 2nd option is more appealing as there is less likelihood of a service name conflict.
