### ISSUE TITLE
forceTimeSoze not forceTimeZone

### ISSUE THREAD

**Issue by rickjury** [SumoLogic/sumologic-collector-chef-cookbook#68]
there is a typo in  https://github.com/SumoLogic/sumologic-collector-chef-cookbook/blob/master/libraries/provider_source.rb#L55 

forceTimeSoze not forceTimeZone

This results in invalid json being generated if we try to set the forceTimeZone attribute.

**Comment by duchatran** [comment]
Fixed with Pull #67
