### ISSUE TITLE
Pull request #64 breaks Chef 11 support

### ISSUE THREAD

**Issue by mshepet** [SumoLogic/sumologic-collector-chef-cookbook#69]
We use the sumo cookbook with AWS OpsWorks and Chef 11.10.  Pull request https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/64 seems to break support for Chef 11.   

Cookbook trace below.

<pre><code>
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_docker_source.rb

 
NoMethodError
-------------
undefined method `provides' for Chef::Provider::SumoSource:Class
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_source.rb:7:in `<class:SumoSource>'
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_source.rb:6:in `<class:Provider>'
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_source.rb:5:in `<class:Chef>'
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_source.rb:4:in `<top (required)>'
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_docker_source.rb:2:in `require_relative'
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_docker_source.rb:2:in `<top (required)>
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/sumologic-collector/libraries/provider_source.rb:
 
1:  require 'chef/platform/query_helpers'
2:  require 'chef/provider/lwrp_base'
3:  
4:  class Chef
5:    class Provider
6:      class SumoSource < Chef::Provider::LWRPBase
7>>       provides :sumo_source
8:  
9:        use_inline_resources if defined?(use_inline_resources)
10:  
11:        def whyrun_supported?
12:          false
13:        end
14:  
15:        def load_current_resource
16:          @current_resource = Chef::Resource::SumoSource.new(new_resource.name)</code></pre>

**Comment by duchatran** [comment]
@mshepet: Thanks for letting us now. We have different releases (https://github.com/SumoLogic/sumologic-collector-chef-cookbook/releases) to address this and similar issues - unfortunately this will happen as we leverage newer technology. Will this help or should we need to publish these releases with proper tagging under the Chef supermarket?

**Comment by elyobo** [comment]
@duchatran I can't see from the list which releases are chef 11 compatible and which are not; #76 fixes a chef 11 issue with metadata but then I run into this one.

**Comment by mgdevstack** [comment]
@mshepet @elyobo Hope above merge will solve your problem. This is specifically chef 11 compatibility issue. Same issue is still open for various community cookbooks like [chef-vault](https://github.com/chef-cookbooks/chef-vault/issues/36), [Docker](https://github.com/chef-cookbooks/docker/issues/330) etc.

**Comment by duchatran** [comment]
Thanks @mgdevstack!

**Comment by elyobo** [comment]
Yes, thanks @mgdevstack; I eventually rolled back to something that worked, but will try to upgrade again.
