### ISSUE TITLE
Mixlib::ShellOut::ShellCommandFailed

### ISSUE THREAD

**Issue by sunil-r** [SumoLogic/sumologic-collector-chef-cookbook#91]
getting he below error when i run it form the chef server, but in the client machine it works fine. i tried by setting the env varible as set JAVA_OPTS="-Xms512M -Xmx1024M" but still no luck. 

STDOUT: Preparing JRE ...
Copy-mode.
Copy-mode.
The installation directory has been set to C:\sumo.
Extracting files...

[error occurred during error reporting (null), id 0xc0000005]
# 
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
# An error report file with more information is saved as:

**Comment by zl4bv** [comment]
Hi @sunil-r, would you mind clarifying a couple of things:

* What operating system is the client machine?
* Aside running the cookbook locally versus running it from Chef Server, was anything else different that made the install work fine?

**Comment by sunil-r** [comment]
Hi Ben,
The client machine is “windows server 2010r2” ,
there is no difference, I am using the same cook book and the same run list and same parameters.

**Comment by sunil-r** [comment]
Hi Ben,
The client machine is “windows server 2010r2” ,
there is no difference, I am using the same cook book and the same run list and same parameters.

I think this is more to do with the SumoCollector_windows-x64.exe, which is trying to run the java to install sumologic, and it is running out of memory since it has not set the min max memory for running java.

Regards,
Sunil.R

**Comment by majormoses** [comment]
I think this might help: https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/128

**Comment by majormoses** [comment]
closing due to lack of response
