### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by zl4bv** [SumoLogic/sumologic-collector-chef-cookbook#92]
[Without a license](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license), Sumo Logic retains all rights to the source code and nobody else may reproduce, distribute, or create derivative works from this work. I believe that by having the source to this cookbook publicly available, it is not the intention of Sumo Logic to have the aforementioned default copyright laws applied to this cookbook.

Chef [prefer](https://github.com/chef-partners/cookbook-guide/blob/master/docs/04_how_to_write_a_good_cookbook.md) the Apache 2.0 license on their works, however the choice is completely up to Sumo Logic and should be documented somewhere in this repository.

**Comment by sumotravisci** [comment]
@zl4bv : just see this now. Let me check with the team quickly - we usually do Apache 2.0.

**Comment by duchatran** [comment]
Done. https://github.com/SumoLogic/sumologic-collector-chef-cookbook/pull/100

**Comment by duchatran** [comment]
Added.
